#!/usr/bin/env python3
"""
APEX Auto Issue Writer
Reads today's action queue and creates GitHub Issues for P0/P1 findings.
Fully autonomous — no human approval needed.
"""

import os
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone

try:
    import requests
except ImportError:
    print("requests not available — skipping issue creation")
    exit(0)

def create_issue(token: str, repo: str, title: str, body: str, labels: list):
    r = requests.post(
        f"https://api.github.com/repos/{repo}/issues",
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
        },
        json={"title": title, "body": body, "labels": labels},
        timeout=15
    )
    return r.status_code, r.json()

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--auto-approve", action="store_true", default=True)
    args = parser.parse_args()

    token = os.environ.get("GITHUB_TOKEN", "")
    repo = os.environ.get("GITHUB_REPO", "GlacierEQ/apex-control-plane")
    if not token:
        print("No GITHUB_TOKEN — skipping issue creation")
        return

    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    q_path = Path(f"action_queue/queue_{date_str}.json")
    if not q_path.exists():
        print(f"No queue file found at {q_path}")
        return

    queue = json.loads(q_path.read_text())
    created = 0

    for item in queue:
        if item["severity"] not in ("P0", "P1"):
            continue
        title = f"[{item['severity']}] {item['title']}"
        body = (
            f"## Auto-generated by APEX Daily Runner\n\n"
            f"**Severity:** `{item['severity']}`\n"
            f"**Action:** {item['action']}\n"
            f"**Auto-executable:** {item['auto_execute']}\n\n"
            f"*Generated: {date_str} — No human approval required*"
        )
        labels = [item["severity"].lower(), "apex-audit", "auto-generated"]
        status, resp = create_issue(token, repo, title, body, labels)
        if status == 201:
            print(f"✅ Issue created: #{resp.get('number')} — {title}")
            created += 1
        else:
            print(f"⚠️  Issue creation failed ({status}): {resp.get('message')}")

    print(f"\nIssues created: {created}")

if __name__ == "__main__":
    main()
