import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const H={"content-type":"application/json","cache-control":"no-store, max-age=0"};const enc=new TextEncoder();
function j(s:number,b:unknown){return new Response(JSON.stringify(b),{status:s,headers:H});}
function d64(s:string){const x=atob(s);return Uint8Array.from(x,c=>c.charCodeAt(0));}
function b64(b:Uint8Array){let x="";for(let i=0;i<b.length;i+=0x8000)x+=String.fromCharCode(...b.subarray(i,i+0x8000));return btoa(x);}
function der(p:string){const q=p.trim().replace("-----BEGIN PRIVATE KEY-----","").replace("-----END PRIVATE KEY-----","").replace(/\s+/g,"");const b=d64(q);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);}
async function get(c:any,path:string){const host=`iaas.${c.region}.oci.oraclecloud.com`,date=new Date().toUTCString(),str=`(request-target): get ${path}\nhost: ${host}\ndate: ${date}`,key=await crypto.subtle.importKey("pkcs8",der(c.private_key_pem),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]),sig=b64(new Uint8Array(await crypto.subtle.sign({name:"RSASSA-PKCS1-v1_5"},key,enc.encode(str)))),auth=`Signature version="1",keyId="${c.tenancy_ocid}/${c.user_ocid}/${c.fingerprint}",algorithm="rsa-sha256",headers="(request-target) host date",signature="${sig}"`;const r=await fetch(`https://${host}${path}`,{headers:{date,authorization:auth,accept:"application/json"},signal:AbortSignal.timeout(15000)});const t=await r.text();let p:any=null;try{p=t?JSON.parse(t):null}catch{p={body_length:t.length}};return{ok:r.ok,status:r.status,payload:p};}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return j(405,{error:"method_not_allowed"});const url=Deno.env.get("SUPABASE_URL"),sr=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!sr)return j(500,{error:"configuration_missing"});const a=createClient(url,sr,{auth:{persistSession:false,autoRefreshToken:false}});const gate=await a.rpc("claim_apex_oci_census_gate");if(gate.error||gate.data?.ok!==true)return j(401,{error:gate.error?.message||gate.data?.error||"gate_rejected"});try{const m=await a.from("apex_keymaster_secrets").select("secret_ref").eq("provider","oracle").eq("status","active").eq("verification_status","verified").order("created_at",{ascending:false}).limit(1).maybeSingle();if(m.error||!m.data?.secret_ref)throw new Error("oracle_secret_missing");const r=await a.rpc("resolve_apex_keymaster_secret_for_broker",{p_secret_ref:m.data.secret_ref,p_provider:"oracle",p_request_id:`oci-inspect-${Date.now()}`,p_actor:"apex-oci-instance-inspect-once",p_operation:"inspect_existing_compute"});if(r.error||typeof r.data?.secret!=="string")throw new Error(r.error?.message||"secret_resolution_failed");let s=r.data.secret as string;const c=JSON.parse(s);s="";const inv=await a.from("apex_oci_resource_inventory_v1").select("identifier,display_name,compartment_id").eq("resource_type","Instance").eq("lifecycle_state","RUNNING").order("observed_at",{ascending:false}).limit(1).maybeSingle();if(inv.error||!inv.data?.identifier)throw new Error("running_instance_missing");const id=inv.data.identifier,comp=inv.data.compartment_id||c.tenancy_ocid;const instance=await get(c,`/20160918/instances/${encodeURIComponent(id)}`);if(!instance.ok)throw new Error(`instance_get_http_${instance.status}`);const va=await get(c,`/20160918/vnicAttachments?compartmentId=${encodeURIComponent(comp)}&instanceId=${encodeURIComponent(id)}&limit=100`);const attachments=Array.isArray(va.payload)?va.payload:[];let vnic:any=null;if(attachments[0]?.vnicId){const vr=await get(c,`/20160918/vnics/${encodeURIComponent(attachments[0].vnicId)}`);if(vr.ok)vnic=vr.payload;}
const target={instance_id:id,display_name:instance.payload?.displayName||inv.data.display_name||null,lifecycle_state:instance.payload?.lifecycleState||null,shape:instance.payload?.shape||null,shape_config:instance.payload?.shapeConfig||null,image_id:instance.payload?.imageId||null,availability_domain:instance.payload?.availabilityDomain||null,fault_domain:instance.payload?.faultDomain||null,subnet_id:vnic?.subnetId||null,vnic_id:vnic?.id||attachments[0]?.vnicId||null,public_ip:vnic?.publicIp||null,private_ip:vnic?.privateIp||null,hostname_label:vnic?.hostnameLabel||null,vnic_lifecycle_state:vnic?.lifecycleState||null,inspected_at:new Date().toISOString()};const up=await a.from("apex_oci_control_state_v1").update({selected_targets:target,updated_at:new Date().toISOString()}).eq("control_key","oracle-primary");if(up.error)throw new Error(`target_write_failed:${up.error.message}`);await a.rpc("complete_apex_oci_census_gate",{p_error:null});return j(200,{ok:true,target});}catch(e){const m=e instanceof Error?e.message:"inspect_failed";await a.rpc("complete_apex_oci_census_gate",{p_error:m.slice(0,256)});return j(400,{ok:false,error:m.slice(0,256)});}});